services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
      args:
        - BASE_IMAGE=${BASE_IMAGE}
    image: ${IMAGE_NAME:-uclv-judge-tier3}:${IMAGE_TAG:-latest}
    cap_add:
      - SYS_PTRACE
