version: "3.9"
services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
    image: dmoj/judge-tier3:${IMAGE_TAG:-latest}
    command: run -c /judge.yml "${BRIDGE_ADDRESS:-10.12.101.21}" "$JUDGE_NAME" "$JUDGE_KEY"
    volumes:
      - ${PROBLEMS_DIR:-/mnt/dmoj/problems}:/problems:ro
    cap_add:
      - SYS_PTRACE
    restart: always
