name: ${PROJECT_NAME}

services:
  app:
    image: ${IMAGE:-uclv-judge-tier3:active}
    command: run --skip-self-test "${BRIDGE_ADDRESS:-10.12.101.21}"
    environment:
      DMOJ_JUDGE_NAME: "$JUDGE_NAME"
      DMOJ_JUDGE_KEY: "$JUDGE_KEY"
    volumes:
      - ${PROBLEMS_DIR:-/var/opt/lib/dmoj/problems}:/problems:ro
    cap_add:
      - SYS_PTRACE
    restart: unless-stopped
