name: ${PROJECT_NAME}

services:
  judge:
    image: ${IMAGE:-uclv-judge-tier3:active}
    command: ["run", "--skip-self-test", "-c /judge.yml", "$BRIDGE_ADDRESS"]
    environment:
      DMOJ_JUDGE_NAME:
    env_file:
      - .key
    volumes:
      - ${PROBLEMS_DIR:-/var/opt/lib/dmoj/problems}:/problems:ro
    cap_add:
      - SYS_PTRACE
    restart: unless-stopped
