version: "3.9"
services:
  app:
    build:
      context: .
    command: inotifywait -m -r -e modify,move,create,delete /problems
    volumes:
      - ${PROBLEMS_DIR:-/var/opt/lib/dmoj/problems}:/problems:ro
    restart: unless-stopped
