id: main-judge-1

key: ""

problem_storage_root:
- /mnt/problems

runtime:
  as_x64: /usr/bin/x86_64-linux-gnu-as
  as_x86: /usr/bin/as
  awk: /usr/bin/mawk
  cargo: /home/judge/.cargo/bin/cargo
  cat: /bin/cat
  chicken-csc: /usr/bin/chicken-csc
  clang: /usr/bin/clang
  clang++: /usr/bin/clang++
  cobc: /usr/bin/cobc
  coffee: /usr/bin/coffee
  dart: /usr/bin/dart
  dmd: /usr/bin/dmd
  fpc: /usr/bin/fpc
  fsharpc: /usr/bin/fsharpc
  g++: /usr/bin/g++
  g++11: /usr/bin/g++
  g++14: /usr/bin/g++
  g++17: /usr/bin/g++
  g++20: /usr/bin/g++-11
  gcc: /usr/bin/gcc
  gcc11: /usr/bin/gcc
  gforth: /usr/bin/gforth
  gfortran: /usr/bin/gfortran
  ghc: /usr/bin/ghc
  gnatmake: /usr/bin/gnatmake
  go: /usr/bin/go
  ick: /usr/bin/ick
  java15: /usr/lib/jvm/java-15-openjdk-amd64/bin/java
  java8: /usr/lib/jvm/java-8-openjdk-amd64/bin/java
  javac15: /usr/lib/jvm/java-15-openjdk-amd64/bin/javac
  javac8: /usr/lib/jvm/java-8-openjdk-amd64/bin/javac
  kotlin_vm: /usr/bin/java
  kotlinc: /opt/kotlin/bin/kotlinc
  ld_x64: /usr/bin/x86_64-linux-gnu-ld
  ld_x86: /usr/bin/ld
  lua: /usr/bin/lua
  mono: /usr/bin/mono
  mono-csc: /usr/bin/mono-csc
  mono-vbnc: /usr/bin/vbnc
  nasm: /usr/bin/nasm
  node: /usr/bin/nodejs
  ocamlfind: /home/judge/.opam/default/bin/ocamlfind
  perl: /usr/bin/perl
  php: /usr/bin/php
  pike: /usr/bin/pike
  pypy: /opt/pypy2/bin/pypy
  pypy3: /opt/pypy3/bin/pypy3
  python: /usr/bin/python2.7
  python3: /usr/bin/python3
  racket: /usr/bin/racket
  raco: /usr/bin/raco
  ruby2: /usr/bin/ruby2.7
  sbcl: /usr/bin/sbcl
  scala_args:
  - -Xbootclasspath/a:/usr/share/scala-2.11/lib/hawtjni-runtime.jar:/usr/share/scala-2.11/lib/jansi.jar:/usr/share/scala-2.11/lib/jline.jar:/usr/share/scala-2.11/lib/scala-actors.jar:/usr/share/scala-2.11/lib/scala-compiler.jar:/usr/share/scala-2.11/lib/scala-library.jar:/usr/share/scala-2.11/lib/scala-parser-combinators.jar:/usr/share/scala-2.11/lib/scala-reflect.jar:/usr/share/scala-2.11/lib/scala-xml.jar:/usr/share/scala-2.11/lib/scalap.jar
  - -classpath
  - '''""'''
  - -Dscala.boot.class.path=/usr/share/scala-2.11/lib/hawtjni-runtime.jar:/usr/share/scala-2.11/lib/jansi.jar:/usr/share/scala-2.11/lib/jline.jar:/usr/share/scala-2.11/lib/scala-actors.jar:/usr/share/scala-2.11/lib/scala-compiler.jar:/usr/share/scala-2.11/lib/scala-library.jar:/usr/share/scala-2.11/lib/scala-parser-combinators.jar:/usr/share/scala-2.11/lib/scala-reflect.jar:/usr/share/scala-2.11/lib/scala-xml.jar:/usr/share/scala-2.11/lib/scalap.jar
  - -Dscala.home=/usr/share/scala-2.11
  - -Dscala.usejavacp=true
  - -Denv.emacs=
  - scala.tools.nsc.MainGenericRunner
  scala_vm: /usr/bin/java
  scalac: /usr/bin/scalac
  sed: /bin/sed
  swiftc: /opt/swift/usr/bin/swiftc
  swipl: /usr/bin/swipl
  tclsh: /usr/bin/tclsh
  tprolog: /opt/tprolog/tprolog
  tprologc: /opt/tprolog/tprologc
  v8dmoj: /usr/bin/v8dmoj
  zig: /opt/zig/zig
  crt_x86_in_lib32: true
